language: go
go:
  - 1.11.5

jobs:
  include:
    - stage: unit tests
      if: branch = master
      script: 
        #- go test ./... -v -covermode=count -coverprofile=coverage.out
        - go test -json > report.json
        - go test -coverprofile=coverage.out
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
        - ls
        - sonar-scanner
      os: 
        - linux
        - windows
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go get github.com/jinzhu/gorm
        - go get github.com/mattn/go-sqlite3
        - go get github.com/sirupsen/logrus
        - go get github.com/gorilla/sessions
        - go get github.com/c-bata/go-prompt


addons:
  sonarcloud:
    #organization: "sonarcloud"
    token: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
